Exclude subfields
NatLibFi/marc-record-merge-js pull request #59
Opened 2020-10-29 16:25 UTC by ssilvonen

I can't figure out how to implement excluding subfields in copy.js (lines 60-69)

2020-10-30 08:23 UTC, natlibfi-arlehiko requested changes
Your branch conflicts with base. Did you pull next before creating a new branch? Pull changes to `next` now and then in this branch do: `git merge next`

2020-10-30 08:23 UTC, natlibfi-arlehiko commented on src/reducers/copy.js
> +            function isIdenticalSubfield(baseSub) {
You would use `excludeSubfields` here.

2020-10-30 08:23 UTC, natlibfi-arlehiko commented on src/reducers/copy.js
> +    if (compareTagsOnly === false) {
`compareTagsOnly` is much simpler & shorter so it would be better to do the implementation this way `if (compareTagsOnly) {`

2020-11-02 07:46 UTC, natlibfi-arlehiko requested changes

2020-11-02 07:46 UTC, natlibfi-arlehiko commented on src/reducers/copy.js
> +                  const excludedSubfields = [...excludeSubfields]; // make array from string
Should not be a string. Should be an array of strings which is passed to reducer creation function.

2020-11-02 07:46 UTC, natlibfi-arlehiko commented on src/reducers/copy.js
> +                if(!excludeSubfields) {
Not needed. You only need `if (excludeSubfields) {` and then return from that block

2020-11-02 07:46 UTC, natlibfi-arlehiko commented on src/reducers/copy.js
> +                  function filterExcluded(subfield) {
Declare functions at the end of the disclosing function.

2020-11-16 11:09 UTC, natlibfi-jonollil commented on src/reducers/select.js
>    if (baseField.tag === sourceField.tag === false) {
if (baseField.tag !== sourceField.tag) {

2023-08-10 14:22 UTC, closed without merging