muuntaja copy features & maintenance
NatLibFi/marc-record-merge-js pull request #60
Opened 2022-05-31 06:24 UTC by natlibfi-jonollil

- Updated tests
- Added new copy features for Muuntaja
- Removed drone
- Added GitHub Actions

2022-05-31 15:00 UTC, ammsalme requested changes

2022-06-01 05:26 UTC, natlibfi-jonollil commented on src/reducers/copy.js
> +    const baseCompareFields = baseFields.map(baseField => createCompareField(baseField));
Nope. Fixed

2022-06-02 09:53 UTC, nvolk approved these changes
Näyttäisi, että muutokset vievät asioita eteenpäin, joten kelpaa mulle. Yritän katsoa kokonaislogiikkaa vielä tällä viikolla ajatuksella, mutta jos sieltä löytyisi jotain, niin se ei liity näihin fikseihin.

Pieni sivuhuomautus: compareWithoutIndicators testaa 010-kentän indikaattoreita. Testejä voisi muokata sellaiseksi, joissa indikaattoreilla on oikeasti merkitystä (esim. 650 ind2=0 vs ind2=2), jolloin testin logiikka olisi selvempi ja testi perustelisi paremmin olemassaolonsa.
 
 "basic only" -hakemisto pitäs varmaan nimetä camel casena muodossa basicOnly, varsinkin kun välilyönnit hakemistojen nimissä on tylsiä...

2022-06-14 09:19 UTC, natlibfi-jonollil commented
> "basic only" -hakemisto pitäs varmaan nimetä camel casena muodossa basicOnly, varsinkin kun välilyönnit hakemistojen nimissä on tylsiä...
"basic copy"  folder contains test that test only basic functionality of copy, Other folders are named by option they test.
"basic copy" -> renamed to copy
There maybe should be folder multiOptions or something like that where different combinations of options would be tested.

2023-08-10 14:19 UTC, merged